services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf

  data-storage:
    build: ../services/data-storage
    container_name: data-storage
    volumes:
      - ../data:/app/data
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    depends_on:
      - mqtt-broker

  dashboard-backend:
    build:
      context: ../services/dashboard-backend
    container_name: dashboard-backend
    ports:
      - "8000:8000"
    depends_on:
      - data-storage
      - mqtt-broker

  risk-analysis:
    build: ../services/risk_analysis
    container_name: risk-analysis
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    depends_on:
      - mqtt-broker

  alert-notification:
    build: ../services/alert_notification
    container_name: alert-notification
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    depends_on:
      - mqtt-broker
